In [2]:
import numpy as np

In [4]:
arr=np.ones(10)*5
print(arr)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [7]:
arr=np.arange(10,51)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [9]:
arr=np.arange(10,51,2)
print(arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [12]:
arr=np.arange(0,9)
arr1=arr.reshape(3,3)
print(arr1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [17]:
arr=np.random.normal(1,10,25)
print(arr)

[  4.12136262  -6.56247473   4.99807967   7.07405889  17.52209767
  -2.89488204   6.38700044  -6.82831993   9.54158689 -12.07163922
  -3.86630003  -0.07774497   6.17499166  -4.48771101  -8.45170875
   2.59238179   0.16645067   1.55755472 -10.43772895  -1.09002458
  -6.40996821  -0.67570931  14.00378592  15.53667137   3.57470027]


In [20]:
arr=np.arange(0,1,0.01)
print(arr)

[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97
 0.98 0.99]


In [23]:
arr=np.linspace(0,1,20)
print(arr)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [26]:

arr=np.arange(1,26)
arr1=arr.reshape(5,5)
print(arr1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [30]:
print(arr1[2:,1:])

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [32]:
print(arr1[:3,1:2])

[[ 2]
 [ 7]
 [12]]


In [33]:
#sum of all elements in arr
np.sum(arr1)

325

In [39]:
#sum of each column
arr1.sum(axis=0)

array([55, 60, 65, 70, 75])

In [40]:
#sum of each row
arr1.sum(axis=1)

array([ 15,  40,  65,  90, 115])